/**
 * 界面文案集中管理。以后要做 i18n，把这个文件换成按语言加载即可。
 */
export const copy = {
  app: {
    name: 'Make Your Life Better',
    shortName: 'MYLB',
    tagline: '浏览器里的提效小工具，打开就能用',
    privacy: '数据默认只在你的浏览器里处理和保存。登录后可以选择把任务保存到云端。',
    home: '首页',
    allTools: '全部工具',
    notFoundTitle: '页面不存在',
    notFoundBody: '你访问的页面不存在，可能是链接写错了。',
    backHome: '回到首页',
    errorTitle: '页面出错了',
    errorBody: '加载这个页面时出现问题，可以刷新重试。',
    reload: '刷新',
    loading: '加载中…',
  },
  toolStatus: {
    new: '新',
    beta: '测试中',
    stable: '',
  },
  account: {
    login: '登录',
    account: '账号',
    title: '账号',
    loginTitle: '登录 / 注册',
    loginDesc: '登录后可以把任务保存到云端，换台电脑也能打开。不登录也能正常使用所有工具。',
    unavailable: '账号服务暂时不可用。所有工具仍然可以正常使用，只是不能保存到云端。',
    byCode: '验证码登录',
    byPassword: '密码登录',
    email: '邮箱',
    emailPlaceholder: 'you@example.com',
    code: '验证码',
    codePlaceholder: '6 位数字',
    sendCode: '发送验证码',
    resendIn: (s: number) => `${s} 秒后可重发`,
    codeSent: (email: string) => `验证码已发送到 ${email}，10 分钟内有效。`,
    autoRegister: '没有账号时，用验证码登录会自动注册。',
    password: '密码',
    submitLogin: '登录',
    noPasswordHint: '还没设置过密码？先用验证码登录，再到账号页设置。',
    loggedInAs: '当前账号',
    logout: '退出登录',
    usageTitle: '云端空间',
    usage: (used: string, quota: string) => `已用 ${used} / ${quota}`,
    tasks: (n: number, max: number) => `${n} / ${max} 个任务`,
    passwordTitle: (has: boolean) => (has ? '修改密码' : '设置密码'),
    passwordDesc: '设置后可以用邮箱 + 密码登录。修改后，其他设备会退出登录。',
    newPassword: '新密码（至少 8 位）',
    savePassword: '保存密码',
    passwordSaved: '密码已保存',
    dangerTitle: '删除账号',
    dangerDesc: '账号和所有云端任务、文件都会被永久删除，不能恢复。本机浏览器里的数据不受影响。',
    deleteAccount: '删除账号',
    confirmDelete: '确认删除（不能恢复）',
    cancel: '取消',
    genericError: '操作失败，请稍后再试',
  },
  theme: {
    menuLabel: '主题设置',
    modeLabel: '显示模式',
    light: '浅色',
    dark: '深色',
    system: '跟随系统',
    presetLabel: '主题配色',
  },
} as const
