/** Excel 对比工具的界面文案 */
export const t = {
  title: 'Excel 数据对比',
  subtitle: '上传 2～3 个 xlsx / csv 文件，按主键匹配后逐字段对比差异。',
  steps: ['上传文件', '选择工作表', '配置字段', '查看结果'] as const,
  prev: '上一步',
  next: '下一步',
  restart: '重新开始',

  upload: {
    dropTitle: '拖拽文件到这里，或点击选择',
    dropHint: '支持 .xlsx 和 .csv，一次 2～3 个文件',
    dropFull: '已经有 3 个文件了，删掉一个才能再添加',
    inspecting: '正在读取…',
    sheets: (n: number) => `${n} 个工作表`,
    csv: (enc: string | null) => `CSV · ${enc === 'gb18030' ? 'GBK' : 'UTF-8'}`,
    large: '文件较大，解析可能要一些时间',
    remove: '移除',
    needMore: (n: number) => `还需要再添加 ${n} 个文件`,
    waitParsing: '等文件读取完成后再继续',
    fixErrors: '有文件读取失败，请移除后重新上传',
    sampleTitle: '手边没有文件？',
    sampleBody: '可以先载入示例文件试试。示例里故意放了大标题、列名不一致、日期格式不同、空格、缺失、主键重复这些常见问题。',
    sampleSmall: '示例：3 个文件 × 1,000 行',
    samplePerf: '性能测试：3 个文件 × 10 万行',
    sampleLoading: '正在生成…',
  },

  sheet: {
    sheet: '工作表',
    headerRow: '表头在第几行',
    encoding: '编码',
    encodingAuto: (current: string | null) => `自动识别（${current === 'gb18030' ? 'GBK' : 'UTF-8'}）`,
    rows: (n: number) => `共 ${n.toLocaleString()} 行`,
    previewHint: '点击左侧行号可以把那一行设为表头',
    loading: '正在读取工作表…',
    extracting: '正在解析…',
  },

  fields: {
    title: '字段映射',
    desc: '同名的列已经自动配对。列名不一样的（比如"工号"和"员工编号"），在对应文件的下拉框里手动选。',
    colField: '字段',
    colRole: '用途',
    none: '（无）',
    roles: { key: '主键', compare: '对比', display: '只展示', ignore: '忽略' },
    roleHelp: '主键：用来匹配同一条记录，可以选多个组成组合主键。对比：逐个比较各文件的值。只展示：放在结果里方便辨认，不比较。',
    normalizeTitle: '比较规则',
    normalizeDefault: '始终生效：去掉首尾空格；空单元格和 "null" 视为相同；数字按数值比较（1 = 1.0 = 1,000 这类写法）；日期统一成年-月-日再比较。',
    ignoreCase: '忽略大小写',
    fullToHalf: '全角转半角（Ａ１ = A1）',
    keepLeadingZeros: '保留前导零（001 ≠ 1）',
    keepLeadingZerosHint: '工号、身份证这类编号建议打开',
    run: '开始对比',
    running: '正在对比…',
    rerun: '重新对比',
  },

  result: {
    summary: {
      all: '全部',
      diff: '有差异',
      missing: '有缺失',
      equal: '全部一致',
      duplicateKey: '主键重复',
      emptyKey: '主键为空',
      overlapHint: '一行可能同时属于多类',
    },
    keySearch: '搜索主键…',
    onlyDiffColumns: '只显示有差异的列',
    statusCol: '状态',
    missingIn: (letter: string) => `缺 ${letter}`,
    elapsed: (ms: number, rows: number) => `${rows.toLocaleString()} 行 · 对比用时 ${ms.toFixed(0)} ms`,
    missingCell: '—',
    adjust: '调整配置',
    configTitle: '调整对比配置',
    configDesc: '修改字段映射或比较规则后，点"重新对比"。',
    rowHint: '点击任意一行查看详情',
    empty: '没有符合条件的行',
  },

  excluded: {
    title: '未参与对比的行',
    desc: '主键为空、或者主键在某个文件里重复的行，没法确定该和哪一行比较，所以单独列在这里。',
    file: '文件',
    row: '行号',
    key: '主键',
    reason: '原因',
    emptyKey: '主键为空',
    duplicateIn: (letters: string) => `主键在 ${letters} 中重复`,
    more: (n: number) => `还有 ${n.toLocaleString()} 行未显示`,
  },

  detail: {
    title: '记录详情',
    field: '字段',
    notInFile: '该文件中没有这条记录',
    notMapped: '（未映射）',
  },
}
